---
- name: Check that Passwords Variables are set correctly 
  ansible.builtin.assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: true
  loop:
    - "{{ rabbit_to_slack_rabbit_pw }}"
  no_log: true
  tags:
    - rabbit_to_slack_install

- name: Check that String Variables are set correctly 
  ansible.builtin.assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: true
  loop:
    - "{{ env_class }}"
    - "{{ env_name }}"
    - "{{ env_region }}"
    - "{{ env_qm_connection }}"
    - "{{ rabbit_to_slack_git_branch }}"
    - "{{ rabbit_to_slack_workdir }}"
    - "{{ rabbit_to_slack_rabbit_host }}"
    - "{{ rabbit_to_slack_rabbit_user }}"
    - "{{ rabbit_to_slack_rabbit_queue }}"
    - "{{ rabbit_to_slack_hook }}"
  tags:
    - rabbit_to_slack_install

- name: Check that Integer Variables are set correctly
  ansible.builtin.assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is number }}"
    quiet: true
  loop:
    - "{{ rabbit_to_slack_rabbit_port }}"
  tags:
    - rabbit_to_slack_install
