---
- name: Rabbit-to-slack | Clone repo. branch:'{{ rabbit_to_slack_git_branch }}'
  ansible.builtin.git:
    repo: https://github.com/Kv-126-DevOps/rabbit_to_slack.git
    dest: '{{ rabbit_to_slack_workdir }}'
    version: '{{ rabbit_to_slack_git_branch }}'
    force: true

- name: Rabbit-to-slack | Install python packeges into virtualenv
  ansible.builtin.pip:
    requirements: '{{ rabbit_to_slack_workdir }}/requirements.txt'
    virtualenv: '{{ rabbit_to_slack_workdir }}/venv'
    virtualenv_command: python3 -m venv

- name: Rabbit-to-slack| Copy service
  ansible.builtin.template:
    src: rabbit-to-slack.service.j2
    dest: '/etc/systemd/system/rabbit-to-slack.service'
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - 'Restart rabbit-to-slack.service'

- name: Rabbit-to-slack | Start service
  ansible.builtin.service:
    name: rabbit-to-slack.service
    state: started
    daemon-reload: true
    enabled: true
  become: true
