---
# Global environment
env_class: "environment_class"
env_name: "environment_name"
env_region: "eu-central-1"
env_qm_connection: "SSL/HTTP"

# RDS/PostgreSQL Variables
postgre_host: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'rds_endpoint', on_denied="skip") | path_join,
    region=env_region
  ) | default('rds_endpoint', true) }}
postgre_port: 5432
postgre_usr: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'rds_user', on_denied="skip") | path_join,
    region=env_region
  ) | default('dbuser', true) }}
postgre_pw: >-
  {{ lookup('aws_ssm',
    ('/', env_class, env_name, 'rds_pass', on_denied="skip") | path_join,
    region=env_region
  ) | default('rdspass', true) }}
postgre_db: "postgres"

# AmazonMQ/RabbitMQ Variables
rabbit_host: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'mq_endpoint', on_denied="skip") | path_join,
    region=env_region
  ) | default('mq_endpoint', true) }}

rabbit_port: 5671
rabbit_usr: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'mq_user', on_denied="skip") | path_join,
    region=env_region
  ) | default('mquser', true) }}

rabbit_pw: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'mq_pass', on_denied="skip") | path_join,
    region=env_region,
    decrypt=true
  ) | default('mqpass', true) }}

rabbit_queue: "restapi"

# Git branches
rabbit_to_db_git_branch: "main"

# Paths to services folder
rabbit_to_db_workdir: "/opt/rabbit-to-db"
