---
- name: Check that Passwords Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ rabbit_to_db_postgres_pw }}"
    - "{{ rabbit_to_db_rabbit_pw }}"
  no_log: true
  
- name: Check that String Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ env_class }}"
    - "{{ env_name }}"
    - "{{ env_region }}"
    - "{{ env_qm_connection }}"
    - "{{ rabbit_to_db_git_branch }}"
    - "{{ rabbit_to_db_workdir }}"
    - "{{ rabbit_to_db_postgres_host }}"
    - "{{ rabbit_to_db_postgres_user }}"
    - "{{ rabbit_to_db_postgres_db }}"
    - "{{ rabbit_to_db_rabbit_host }}"
    - "{{ rabbit_to_db_rabbit_user }}"
    - "{{ rabbit_to_db_rabbit_queue }}"

- name: Check that Integer Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is number }}"
    quiet: yes
  loop:
    - "{{ rabbit_to_db_postgres_port }}"
    - "{{ rabbit_to_db_rabbit_port }}"

- name: rabbit-to-db | Clone repo. branch:'{{ rabbit_to_db_git_branch }}'
  git:
    repo: https://github.com/Kv-126-DevOps/rabbit-to-db.git
    dest: '{{ rabbit_to_db_workdir }}'
    version: '{{ rabbit_to_db_git_branch }}'
    force: true

- name: rabbit-to-db | Install python packeges into virtualenv
  pip:
    requirements: '{{ rabbit_to_db_workdir }}/requirements.txt'
    virtualenv: '{{ rabbit_to_db_workdir }}/venv'
    virtualenv_command: python3 -m venv

- name: rabbit-to-db| Copy service
  template:
    src: rabbit-to-db.service.j2
    dest: '/etc/systemd/system/rabbit-to-db.service'
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart rabbit-to-db.service

- name: rabbit-to-db | Start service
  service:
    name: rabbit-to-db.service
    state: started
    daemon-reload: true
    enabled: true
  become: yes
