---
# Git branches
rest_api_git_branch: main

# Paths to services folder
rest_api_workdir: /opt/rest-api

# Variables
rest_api_postgres_host: postgres
rest_api_postgres_port: 5432
rest_api_postgres_user: dbuser
rest_api_postgres_pw: "{{ lookup('aws_ssm', 'dbpass', region='eu-central-1') }}"
rest_api_postgres_db: postgres
