---
- hosts: frontend
  become: yes
  gather_facts: no
  roles:
    - role: common

- hosts: json-filter
  become: yes
  gather_facts: no
  roles:
    - role: common

- hosts: rabbit-to-bd
  become: yes
  gather_facts: no
  roles:
    - role: common

- hosts: rest-api
  become: yes
  gather_facts: no
  roles:
    - role: common
