---
- hosts: json_filter
  become: true
  gather_facts: false
  roles:
    - common
    - json_filter

- hosts: rabbit_to_db
  become: true
  gather_facts: false
  roles:
    - common
    - rabbit_to_db

- hosts: rabbit_to_slack
  become: true
  gather_facts: false
  roles:
    - common
    - rabbit_to_slack

- hosts: rest_api
  become: true
  gather_facts: false
  roles:
    - common
    - rest_api

- hosts: frontend
  become: true
  gather_facts: false
  roles:
    - common
    - frontend
