---
- hosts: json_filter
  become: true
  gather_facts: false
  roles:
    - common
    - json-filter

- hosts: rabbit_to_db
  become: true
  gather_facts: false
  roles:
    - common
    - rabbit-to-bd

- hosts: rabbit_to_slack
  become: true
  gather_facts: false
  roles:
    - common
    - rabbit-to-slack

- hosts: rest_api
  become: true
  gather_facts: false
  roles:
    - common
    - rest-api

- hosts: frontend
  become: true
  gather_facts: false
  roles:
    - common
    - frontend