---
- hosts: json-filter
  become: true
  gather_facts: false
  roles:
    - common
    - json-filter

- hosts: rabbit-to-bd
  become: true
  gather_facts: false
  roles:
    - common
    - rabbit-to-bd

- hosts: rest-api
  become: true
  gather_facts: false
  roles:
    - common
    - rest-api

- hosts: frontend
  become: true
  gather_facts: false
  roles:
    - common
    - frontend
