---
- hosts: json-filter
  become: true
  gather_facts: false
  roles:
    - role: common

- hosts: rabbit-to-bd
  become: true
  gather_facts: false
  roles:
    - role: common

- hosts: rest-api
  become: true
  gather_facts: false
  roles:
    - role: common

- hosts: frontend
  become: true
  gather_facts: false
  roles:
    - role: common
