---
- hosts: json-filter
  become: true
  gather_facts: false
  roles:
    - role: common
    - role: json-filter

- hosts: rabbit-to-bd
  become: true
  gather_facts: false
  roles:
    - role: common
    - role: rabbit-to-bd

- hosts: rest-api
  become: true
  gather_facts: false
  roles:
    - role: common
    - role: rest-api

- hosts: frontend
  become: true
  gather_facts: false
  roles:
    - role: common
    - role: frontend
