---
common_debug_massage: "hElLo tHeRe"

# Default Timezone
common_ntp_timezone: Europe/Kiev

# Drift file path
common_ntp_driftfile: /var/lib/ntp/drift

# Restrict acces on ntp server
common_ntp_restrict:
  - 127.0.0.1
  - ::1

# Default NTP Servers from www.pool.ntp.org
common_ntp_servers:
  - 0.ua.pool.ntp.org iburst
  - 1.ua.pool.ntp.org iburst
  - 2.ua.pool.ntp.org iburst
  - 3.ua.pool.ntp.org iburst


