---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  set -e
  yamllint -c ../../linter_rules/yamllint.yaml .
  ansible-lint -Rr ../../linter_rules/ansiblelint .
platforms:
  - name: common_instance
    image: redbearddog/docker-amazonlinux2:latest
    command: ${MOLECULE_DOCKER_COMMAND:-"/usr/lib/systemd/systemd"}
    privileged: true
    pre_build_image: false
    networks:
      - name: common_docker_network
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  options:
    v: true
    tags: "frontend_molecule"
    extra-vars: "{'frontend_restapi_host': 'rest_api'}"
  config_options:
    defaults:
      stdout_callback: yaml
  log: false  # set to 'true' if you need detailed info about creating platforms instances
scenario:
  test_sequence:
    # - dependency
    - lint
    # - cleanup
    - destroy
    - syntax
    - create
    # - prepare
    - converge
    - idempotence
    # - side_effect
    # - verify
    # - cleanup
    - destroy
verifier:
  name: ansible
