---
# Global environment
env_class: "environment_class"
env_name: "environment_name"
env_region: "eu-central-1"
env_qm_connection: "SSL/HTTP"

# Git branches
rabbit_to_db_git_branch: "5-rabbit-to-db"

# Paths to services folder
rabbit_to_db_workdir: "/opt/rabbit-to-db"

# RDS/PostgreSQL Variables
rabbit_to_db_postgres_host: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'rds_endpoint') | path_join,
    region=env_region
  ) }}
rabbit_to_db_postgres_port: 5432
rabbit_to_db_postgres_user: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'rds_user') | path_join,
    region=env_region
  ) | default('dbuser', true) }}
rabbit_to_db_postgres_pw: >-
  {{ lookup('aws_ssm',
    ('/', env_class, env_name, 'rds_pass') | path_join,
    region=env_region,
    decrypt=true
  ) }}
rabbit_to_db_postgres_db: "postgres"

# AmazonMQ/RabbitMQ Variables
rabbit_to_db_rabbit_host: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'mq_endpoint') | path_join,
    region=env_region
  ) }}
rabbit_to_db_rabbit_port: 5671
rabbit_to_db_rabbit_user: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'mq_user') | path_join,
    region=env_region
  ) | default('mquser', true) }}
rabbit_to_db_rabbit_pw: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'mq_pass') | path_join,
    region=env_region,
    decrypt=true
  ) }}
rabbit_to_db_rabbit_queue: "restapi"
