---
# Git branches
rabbit_to_db_git_branch: develop

# Paths to services folder
rabbit_to_db_workdir: /opt/rabbit-to-db

# systemd unit folder
rabbit_to_db_service_dir: /etc/systemd/system

# Variables
rabbit_to_db_postgres_host: postgres
rabbit_to_db_postgres_port: 5432
rabbit_to_db_postgres_user: dbuser
rabbit_to_db_postgres_pw: dbpass
rabbit_to_db_postgres_db: postgres
rabbit_to_db_rabbit_host: rabbit
rabbit_to_db_rabbit_port: 5672
rabbit_to_db_rabbit_user: mquser
rabbit_to_db_rabbit_pw: mqpass
rabbit_to_db_rabbit_queue: restapi
