---
    - name: json-filter | Clone repo. branch:'{{ json_filter_git_branch }}'
      git:
        repo: https://github.com/Kv-126-DevOps/json-filter.git
        dest: '{{ json_filter_workdir }}'
        version: '{{ json_filter_git_branch }}'
      become: true
      become_user: ec2-user
    
    - name: json-filter | Install python packeges
      pip:
        requirements: '{{ json_filter_workdir }}/requirements.txt'
      vars:
        ansible_python_interpreter: '/usr/bin/python3'
      become: true
      become_user: ec2-user
    
    - name: json-filter | Copy service
      template:
        src: json-filter.service.j2
        dest: '/etc/systemd/system/json-filter.service'
        owner: root
        group: root
        mode: 0644
        backup: true
      notify:
        - systemctl daemon-reload
        - restart json-filter.service
    
    - name: json-filter | Start service
      service:
        name: json-filter.service
        state: started
        enabled: true
