---
- name: json-filter | Clone repo. branch:'{{ json_filter_git_branch }}'
  git:
    repo: https://github.com/Kv-126-DevOps/json-filter.git
    dest: '{{ json_filter_workdir }}'
    version: '{{ json_filter_git_branch }}'

- name: json-filter | Install python packeges into virtualenv
  pip:
    requirements: '{{ json_filter_workdir }}/requirements.txt'
    virtualenv: '{{ json_filter_workdir }}/venv'
    virtualenv_command: python3 -m venv

- name: json-filter | Copy service
  template:
    src: json-filter.service.j2
    dest: '/etc/systemd/system/json-filter.service'
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart json-filter.service

- name: json-filter | Start service
  service:
    name: json-filter.service
    state: started
    enabled: true

- name: checking service status
  command: systemctl status "{{ item }}"
  with_items:
  - json-filter.service
  register: result
  ignore_errors: yes

- name: showing report
  debug:
    var: "{{ result.stdout_lines|list }}"
