---
- name: Check that String Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - ("{{ item is string }}" and "{{ item | length > 0 }}") or "{{ item is number }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ env_class }}"
    - "{{ env_name }}"
    - "{{ env_region }}"
    - "{{ json_filter_git_branch }}"
    - "{{ json_filter_workdir }}"
    - "{{ json_filter_rabbit_host }}"
    - "{{ json_filter_rabbit_user }}"
    - "{{ json_filter_rabbit_pw }}"
    - "{{ json_filter_host }}"
    - "{{ json_filter_queue_slack }}"
    - "{{ json_filter_queue_restapi }}"
    - "{{ json_filter_rabbit_port }}"
  #no_log: true

- name: json-filter | Clone repo. branch:'{{ json_filter_git_branch }}'
  git:
    repo: https://github.com/Kv-126-DevOps/json-filter.git
    dest: '{{ json_filter_workdir }}'
    version: '{{ json_filter_git_branch }}'
    force: true

- name: json-filter | Install python packeges into virtualenv
  pip:
    requirements: '{{ json_filter_workdir }}/requirements.txt'
    virtualenv: '{{ json_filter_workdir }}/venv'
    virtualenv_command: python3 -m venv

- name: json-filter | Copy service
  template:
    src: json-filter.service.j2
    dest: '/etc/systemd/system/json-filter.service'
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart json-filter.service

- name: json-filter | Start service
  service:
    name: json-filter.service
    state: started
    daemon-reload: true
    enabled: true
  become: yes
