---
- name: Check that String Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ frontend_git_branch }}"
    - "{{ frontend_workdir }}"
    - "{{ frontend_restapi_host }}"
  tags:
    - frontend_install

- name: Check that Int Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is number }}"
    quiet: yes
  loop:
    - "{{ frontend_restapi_port }}"
  tags:
    - frontend_install