---
- name: frontend | Clone repo. branch:'{{ frontend_git_branch }}'
  git:
    repo: https://github.com/Kv-126-DevOps/frontend.git
    dest: '{{ frontend_workdir }}'
    version: '{{ frontend_git_branch }}'
  become: true
  become_user: ec2-user

- name: frontend | Install python packeges into virtualenv
  pip:
    requirements: '{{ frontend_workdir }}/requirements.txt'
    virtualenv: '{{ frontend_workdir }}/venv'
  become: true
  become_user: ec2-user

- name: frontend | Copy service
  template:
    src: frontend.service.j2
    dest: '/etc/systemd/system/frontend.service'
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart frontend.service

- name: frontend | Start service
  service:
    name: frontend.service
    state: started
    enabled: true
