---
- name: Check that String Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ frontend_git_branch }}"
    - "{{ frontend_workdir }}"
    - "{{ frontend_restapi_host }}"

- name: Check that IP Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item | ipv4 }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ frontend_restapi_host }}"

- name: Check that Int Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is number }}"
    quiet: yes
  loop:
    - "{{ frontend_restapi_port }}"

- name: frontend | Clone repo. branch:'{{ frontend_git_branch }}'
  git:
    repo: https://github.com/Kv-126-DevOps/frontend.git
    dest: '{{ frontend_workdir }}'
    version: '{{ frontend_git_branch }}'
    force: true

- name: frontend | Install python packeges into virtualenv
  pip:
    requirements: '{{ frontend_workdir }}/requirements.txt'
    virtualenv: '{{ frontend_workdir }}/venv'
    virtualenv_command: python3 -m venv

- name: frontend | Copy service
  template:
    src: frontend.service.j2
    dest: '/etc/systemd/system/frontend.service'
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart frontend.service

- name: frontend | Start service
  service:
    name: frontend.service
    state: started
    daemon-reload: true
    enabled: true
  become: yes
