---
- import_tasks: git.yaml
  tags:
    - never
    - frontend_molecule

- import_tasks: check_vars.yaml
  tags:
    - never
    - frontend_service_install
    - frontend_check_vars
    - frontend_molecule

- import_tasks: frontend.yaml
  tags:
    - never
    - frontend_service_install
    - frontend_install
    - frontend_molecule
