---
# Global environment
env_class: "environment_class"
env_name: "environment_name"
env_region: "eu-central-1"
env_qm_connection: "SSL/HTTP"

# Git branches
rabbit_to_slack_git_branch: "main"

# Paths to services folder
rabbit_to_slack_workdir: "/opt/rabbit-to-slack"

# Variables
rabbit_to_slack_rabbit_host: "rabbit"
rabbit_to_slack_rabbit_port: 5671
rabbit_to_slack_rabbit_user: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'mq_user') | path_join,
    region=env_region
  ) | default('mquser', true) }}
rabbit_to_slack_rabbit_pw: >-
  {{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'mq_pass') | path_join,
    region=env_region,
    decrypt=true
  ) }}
rabbit_to_slack_rabbit_queue: "slack"
rabbit_to_slack_hook: "webhook_url"
