---
# Git branches
rabbit_to_slack_git_branch: amazon_mq

# Paths to services folder
rabbit_to_slack_workdir: /opt/rabbit-to-slack

# Variables
rabbit_to_slack_rabbit_host: rabbit
rabbit_to_slack_rabbit_port: 5671
rabbit_to_slack_rabbit_user: mquser
rabbit_to_slack_rabbit_pw: "{{ lookup('aws_ssm', 'mqpass', region='eu-central-1') }}"
rabbit_to_slack_rabbit_queue: slack
rabbit_to_slack_hook: url
