---
# Git branches
rabbit_to_slack_git_branch: main

# Paths to services folder
rabbit_to_slack_workdir: /opt/rabbit-to-slack

# Variables
rabbit_to_slack_rabbit_host: rabbit
rabbit_to_slack_rabbit_port: 5671
rabbit_to_slack_rabbit_user: mquser
rabbit_to_slack_rabbit_pw: mqpass
rabbit_to_slack_rabbit_queue: slack
