pipeline {
    agent any

    options {
        ansiColor('vga')
        disableConcurrentBuilds()  // Do not run 2 concurrent builds at the same time
        buildDiscarder logRotator(numToKeepStr: '10')  // Maximum number of builds to save
    }
    stages {
        stage('1-Checkout') {
            steps {
                git branch: '26-ansible-add-jenkins-server-installation', url: 'https://github.com/Kv-126-DevOps/ansible.git'
            }
        }
        stage('2-Execute') {
            steps {
                ansiblePlaybook credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'Ansible', inventory: 'ansible_plugins/aws_ec2.yaml', playbook: 'site.yaml'
            }
        }
    }
}
