---
- name: restart ntp
  service:
    name: ntpd
    state: restarted

- name: restart ssh
  service:
    name: sshd
    state: restarted

- name: restart jenkins
  service: name=jenkins state=restarted

- name: configure default users
  template:
    src: basic-security.groovy.j2
    dest: "{{ jenkins_home }}/init.groovy.d/basic-security.groovy"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  register: jenkins_users_config