---
- name: Include OS-specific variables
#  include_vars: "{{ ansible_distribution }}.yml"
  ansible.builtin.nclude_vars: java_veriable.yaml

- name: Define java_packages.
  ansible.builtin.set_fact:
    java_packages: "{{ __java_packages | list }}"
  when: java_packages is not defined

# Setup/install tasks.
- name: Ensure Java is installed.
  ansible.builtin.package:
    name: "{{ java_packages }}"
    state: present
