
- name: Install epel repositories
      become: yes
      shell: amazon-linux-extras install epel -y

- name: Enable epel repositories
      become: yes
      shell: yum-config-manager --enable epel

- name: Retrieve the installed packages
  package_facts:

- name: Get only list of name of installed packages
  set_fact:
     installed_packages: "{{ ansible_facts.packages.keys() }}"

- name: Find missing packages
  set_fact:
    missing_packages: "{{ required_pkgs | difference (installed_packages) }}"

- name: Install missing packages
  package:
    name: "{{ missing_packages }}"
    state: present
    skip_broken: true
