---

- name: copy MOTD and banner files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
  loop:
   - { src: 'templates/motd.j2', dest: '/etc/motd' }
   - { src: 'templates/issue.j2', dest: '/etc/issue' }
   - { src: 'templates/issue.j2', dest: '/etc/issue.net' }
