---
- name: Check that String Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ common_ntp_timezone }}"
    - "{{ common_ntp_driftfile }}"
    - "{{ common_required_package | join(',') }}"

- name: Check that List Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is list }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:

    - "{{ common_ntp_restrict.split(',').values() | list }}"
    - "{{ common_ntp_servers.split(',').values() | list }}"

- name: Check that Integer Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is number }}"
    quiet: yes
  loop:
    - "{{ common_protection }}"
