---
- name: 'Check that String Variables are set correctly'
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ common_ntp_timezone }}"
    - "{{ common_ntp_driftfile }}"
  tags:
    - common_ntp_install

- name: 'Check that String Variables are set correctly'
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is iterable }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ common_ntp_restrict }}"
    - "{{ common_ntp_servers }}"
  tags:
    - common_ntp_install

- name: 'Check that Integer Variables are set correctly'
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is number }}"
    quiet: yes
  loop:
    - "{{ common_protection }}"
  tags:
    - common_utilities_install

- name: 'Check that String Variables are set correctly'
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is iterable }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ common_required_package }}"
  tags:
    - common_utilities_install
