---
- import_tasks: apps.yaml
  tags:
    - never
    - common_install
    - common_apps_install 

- import_tasks: ntp.yaml
  tags:
    - never
    - common_install
    - common_ntp_install

- import_tasks: banner.yaml
  tags:
    - never
    - common_install
    - common_banner_configure

- import_tasks: ssh.yaml
  tags:
    - never
    - common_install
    - common_ssh_configure

- import_tasks: git.yaml
  tags:
    - never
    - common_install
    - common_git_install

- import_tasks: python-pkg.yaml
  tags:
    - never
    - common_install
    - common_install_python_pkg
