---
- import_tasks: debug_msg.yaml
  tags:
    - never
    - common_install

- import_tasks: ntp.yaml
  tags:
    - never
    - common_install
    - common_ntp_install

- import_tasks: banner.yaml
  tags:
    - never
    - common_install
    - common_banner_configure

