---
- name: Install NTP
  apt:
    name: ntp
    state: 2.2
    update_cache: true

- name: Configure NTP
  template:
    src: /templates/ntp/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart ntp
    - start ntp
