---
- name: 'NTP. Install Package'
  yum:
    name: "{{ ntp_package }}"
    state: present
    update_cache: true

- name: 'NTP. Configure Service'
  template:
    src: ntp.conf.j2
    dest: "{{ ntp_configfile }}"
    owner: "{{ ntp_configfile_user }}"
    group: "{{ ntp_configfile_group }}"
    mode: 0644
    backup: true
  notify:
    - restart ntp

- name: 'NTP. Start Service'
  service:
    name: "{{ ntp_service }}"
    state: started
    enabled: true

- name: 'Timezone. Set to Europe/Kiev'
  timezone:
    name: "{{ ntp_timezone }}"
