---
- name: NTP | Check that String Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ common_ntp_timezone }}"
    - "{{ common_ntp_driftfile }}"


- name: NTP | Check that Iterable Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is iterable }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ common_ntp_restrict }}"
    - "{{ common_ntp_servers }}"

- name: 'NTP | Configure Service'
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart ntp

- name: 'NTP | Start Service'
  service:
    name: ntpd
    state: started
    enabled: true

- name: 'NTP | Setting up {{ common_ntp_timezone }} timezone'
  timezone:
    name: "{{ common_ntp_timezone }}"
