---
- name: Install NTP
  yum:
    name: ntp
    state: present
    update_cache: true

- name: Configure NTP
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart ntp
    - start ntp
