---
- name: 'NTP | Configure Service'
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - Restart ntp

- name: 'NTP | Start Service'
  ansible.builtin.service:
    name: ntpd
    state: started
    enabled: true

- name: 'NTP | Setting up {{ common_ntp_timezone }} timezone'
  community.general.timezone:
    name: "{{ common_ntp_timezone }}"
