---
- name: 'NTP. Install Package'
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ package_list }}"

- name: 'NTP. Configure Service'
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart ntp

- name: 'NTP. Start Service'
  service:
    name: ntpd
    state: started
    enabled: true

- name: 'Setting up default timezone'
  timezone:
    name: "{{ ntp_timezone[0] }}"
