---
- name: 'NTP. Install Package'
  yum:
    name: ntp
    state: present
    update_cache: true

- name: 'NTP. Configure Service'
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart ntp

- name: 'NTP. Start Service'
  service:
    name: ntpd
    state: started
    enabled: true

- name: 'Timezone. Set to Europe/Kiev'
  timezone:
    name: Europe/Kiev
