---
- name: Install PIP
  shell: curl https://bootstrap.pypa.io/pip/3.6/get-pip.py | python
  become: true

- name: Upgrade pip/ Install python packages
  pip:
    name:
      - pip
      - virtualenv
    extra_args: --upgrade
    executable: pip
  become: true
  become_user: ec2-user
