---
- name: Upgrade pip/ Install python packages
  pip:
    name:
      - pip
      - virtualenv
    extra_args: --upgrade
    executable: pip3
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
  become: true
