---
- name: Install/Update PIP
  shell: curl https://bootstrap.pypa.io/pip/3.5/get-pip.py | python
  become: true

- name: nstall python packages
  pip:
    name:
      - pip
      - virtualenv
    extra_args: --upgrade
    executable: pip
  become: true
  become_user: ec2-user
