---
- name: Update SSH daemon config
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    mode: "0600"
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify: restart ssh

- name: Update SSH client config
  copy:
    src: files/ssh_config
    dest: /etc/ssh/ssh_config
    mode: "0644"
    backup: true
