---
- name: 'Install epel repositories'
  shell: amazon-linux-extras install epel -y
  become: true

- name: 'Enable epel repositories'
  shell: yum-config-manager --enable epel
  become: true

- name: 'Disable repository priority protections'
  template:
    src: priorities.conf.j2
    dest: /etc/yum/pluginconf.d/priorities.conf
    owner: root
    group: root
    mode: 0644
    backup: true

- name: "Check if listed package is installed or not"
  package:
    name: "{{ common_required_package }}"
    state: present
    check_mode: true


- name: Install/Update PIP
  shell: curl https://bootstrap.pypa.io/pip/3.5/get-pip.py | python
  become: true

- name: Install python packages
  pip:
    name:
      - pip
      - virtualenv
    extra_args: --upgrade
    executable: pip
  become: true
  become_user: ec2-user
