---
- name: 'Install and enable epel repositories'
  shell: |
    amazon-linux-extras install epel -y
    yum-config-manager --enable epel
  become: true

- name: 'Disable repository priority protections'
  template:
    src: priorities.conf.j2
    dest: /etc/yum/pluginconf.d/priorities.conf
    owner: root
    group: root
    mode: 0644
    backup: true

- name: 'Retrieve the installed packages'
  package_facts:

- name: 'Get list of installed packages'
  set_fact:
    installed_packages: "{{ ansible_facts.packages.keys() }}"

- name: 'Find missing packages'
  set_fact:
    missing_packages: "{{ common_required_package | difference (installed_packages) }}"

- name: 'Install missing packages'
  package:
    name: "{{ missing_packages }}"
    state: present
    update_cache: true

- name: Install/Update PIP
  shell: curl https://bootstrap.pypa.io/pip/3.5/get-pip.py | python
  become: true

- name: Install python packages
  pip:
    name:
      - pip
      - virtualenv
    extra_args: --upgrade
    executable: pip
  become: true
  become_user: ec2-user
