---
- name: 'Utilities | Install and enable epel repositories'
  shell: "{{ item }}"
  loop:
    - amazon-linux-extras install epel -y
    - yum-config-manager --enable epel -y
  become: true

- name: 'Utilities | Disable repository priority protections'
  template:
    src: priorities.conf.j2
    dest: /etc/yum/pluginconf.d/priorities.conf
    owner: root
    group: root
    mode: 0644
    backup: true

- name: 'Utilities | Retrieve the installed packages'
  package_facts:

- name: 'Utilities | Get names of installed packages'
  set_fact:
    installed_packages: "{{ ansible_facts.packages.keys() }}"

- name: 'Utilities | Find missing packages'
  set_fact:
    missing_packages: "{{ common_required_package | difference (installed_packages) }}"

- name: 'Utilities | Install missing packages'
  package:
    name: "{{ missing_packages }}"
    state: present
    update_cache: true

- name: 'Utilities | Install/Update PIP'
  shell: curl https://bootstrap.pypa.io/pip/3.5/get-pip.py | python
  become: true

- name: Install python packages
  pip:
    name:
      - pip
      - virtualenv
    extra_args: --upgrade
    executable: pip
  become: true
  become_user: ec2-user
