---
- name: "Utilities | Install and enable epel repositories"
  ansible.builtin.command: "{{ item }}"
  loop:
    - amazon-linux-extras install epel -y
  become: true
  changed_when: false

- name: "Utilities | Disable repository priority protections"
  ansible.builtin.template:
    src: priorities.conf.j2
    dest: /etc/yum/pluginconf.d/priorities.conf
    owner: root
    group: root
    mode: 0644
    backup: true

- name: "Utilities | Retrieve the installed packages"
  ansible.builtin.package_facts:

- name: "Utilities | Get names of installed packages"
  ansible.builtin.set_fact:
    installed_packages: "{{ ansible_facts.packages.keys() }}"

- name: "Utilities | Find missing packages"
  ansible.builtin.set_fact:
    missing_packages: "{{ common_required_package | difference(installed_packages) }}"

- name: "Utilities | Install missing packages"
  ansible.builtin.package:
    name: "{{ missing_packages }}"
    state: present
    update_cache: true

- name: "Utilities | Download PIP"
  ansible.builtin.get_url:
    url: https://bootstrap.pypa.io/pip/3.5/get-pip.py
    dest: /tmp/get-pip.py
    force: false
    mode: 0644

- name: "Utilities | Install/Update PIP"
  ansible.builtin.command: python /tmp/get-pip.py
  become: true
  changed_when: false

- name: "Install python packages"
  ansible.builtin.pip:
    name:
      - pip
      - virtualenv
    extra_args: --upgrade
    executable: pip
  become: true
#  become_user: ec2-user
