pipeline {
    agent any

    options {
        ansiColor('xterm')
        disableConcurrentBuilds()  // Don't run 2 concurrent builds at the same time
        buildDiscarder logRotator(numToKeepStr: '8')  // Maximum number of builds to save
    }

    parameters {
        ////Extended param for tags
        extendedChoice name: 'ANSIBLE_VERBOSE_FLAG',
                       value: ' , -v, -vv, -vvv, -vvvv',
                       defaultValue: ' ',
                       type: 'PT_SINGLE_SELECT',
                       description: 'Ansible level of verbose'
        //Extended info param for builds list
        extendedChoice name: 'ACTION',
                       value: 'json_filter_install,rabbit_to_db_install,rabbit_to_slack_install,rest_api_install,frontend_install',
                       defaultValue: 'json_filter_install,rabbit_to_db_install,rabbit_to_slack_install,rest_api_install,frontend_install',
                       type: 'PT_CHECKBOX',
                       description: 'Ansible action tags'
        //GitHunb branch param
        gitParameter   name: 'ANSIBLE_BRANCH',
                       defaultValue: 'main',
                       listSize: '4',
                       selectedValue: 'DEFAULT',
                       sortMode: 'DESCENDING_SMART',
                       type: 'PT_BRANCH',
                       quickFilterEnabled: true,
                       useRepository: '.*ansible.git',
                       branchFilter: 'origin/(.*)',
                       description: 'Ansible GitHub branch'
    }

    stages {
        stage ('1-Checkout') {
            steps{
                // Add useful information to build description
                script {
                    currentBuild.description = "ACTION: ${ACTION}\nANSIBLE BRANCH: ${ANSIBLE_BRANCH}\n"
                }
                // Getting ansible repo
                git(
                    poll: true,
                    url: "https://github.com/Kv-126-DevOps/ansible.git",
                    branch: "${params.ANSIBLE_BRANCH}"
                )
            }
        }

        stage('2-Execute') {
            steps {
                ansiblePlaybook(
                    colorized: true,
                    credentialsId: 'private-key',
                    disableHostKeyChecking: true,
                    installation: 'Ansible',
                    inventory: 'ansible_plugins/aws_ec2.yaml',
                    playbook: 'site.yaml',
                    tags: ACTION,
                    extras: ANSIBLE_VERBOSE_FLAG,
                    extraVars:[
                        json_filter_rmq_host: "${MQ_HOST}",
                        json_filter_rmq_pass: "${MQ_PASS}",
                        rabbit_to_db_postgres_host: "${DB_HOST}",
                        rabbit_to_db_postgres_pw: "${DB_PASS}",
                        rabbit_to_db_rabbit_host: "${MQ_HOST}",
                        rabbit_to_db_rabbit_pw: "${MQ_PASS}",
                        rabbit_to_slack_rabbit_host: "${MQ_HOST}",
                        rabbit_to_slack_rabbit_pw: "${MQ_PASS}",
                        rest_api_postgres_host: "${DB_HOST}",
                        rest_api_postgres_pw: "${DB_PASS}",
                        rabbit_to_slack_hook: "${WEB_HOOK}"
                    ]
                )
            }
        }
    }
}
