---
# Git branches
frontend_git_branch: develop

# Paths to services folder
frontend_workdir: /opt/frontend

# systemd unit folder
frontend_service_dir: /etc/systemd/system

# Variables
frontend_restapi_host: localhost
frontend_restapi_port: 5000
