---
# Global environment
env_class: "environment_class"
env_name: "environment_name"
env_region: "eu-central-1"
# Git branches
frontend_git_branch: "main"

# Paths to services folder
frontend_workdir: "/opt/frontend"

# Rest_API Variables
frontend_restapi_host: >-
  {{ lookup('aws_ssm',
    ('/', env_class, env_name, 'rest_api_host' ,on_missing="skip") | path_join,
    region=env_region
  ) | default('rest_api', true) }}

frontend_restapi_port: 5000
