---
# Git branches
frontend_git_branch: "main"

# Paths to services folder
frontend_workdir: "/opt/frontend"

# Rest_API Variables
frontend_restapi_host: >-
  '{{ lookup(
    'aws_ssm',
    ('/', env_class, env_name, 'rest_api_host') | path_join,
    region=env_region
  ) }}'
frontend_restapi_port: 5000
