---
- import_tasks: check_vars.yaml
  tags:
    - never
    - rabbit_to_slack_service_install
    - rabbit_to_slack_check_vars

- import_tasks: rabbit-to-slack.yaml
  tags:
    - never
    - rabbit_to_slack_service_install
    - rabbit_to_slack_install
