---
- name: Check that Passwords Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ rabbit_to_slack_rabbit_pw }}"
  no_log: true
  
- name: Check that String Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ env_class }}"
    - "{{ env_name }}"
    - "{{ env_region }}"
    - "{{ env_qm_connection }}"
    - "{{ rabbit_to_slack_git_branch }}"
    - "{{ rabbit_to_slack_workdir }}"
    - "{{ rabbit_to_slack_rabbit_host }}"
    - "{{ rabbit_to_slack_rabbit_user }}"
    - "{{ rabbit_to_slack_rabbit_queue }}"
    - "{{ rabbit_to_slack_hook }}"

- name: Check that Integer Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is number }}"
    quiet: yes
  loop:
    - "{{ rabbit_to_slack_rabbit_port }}"

- name: rabbit-to-slack | Clone repo. branch:'{{ rabbit_to_slack_git_branch }}'
  git:
    repo: https://github.com/Kv-126-DevOps/rabbit_to_slack.git
    dest: '{{ rabbit_to_slack_workdir }}'
    version: '{{ rabbit_to_slack_git_branch }}'
    force: true

- name: rabbit-to-slack | Install python packeges into virtualenv
  pip:
    requirements: '{{ rabbit_to_slack_workdir }}/requirements.txt'
    virtualenv: '{{ rabbit_to_slack_workdir }}/venv'
    virtualenv_command: python3 -m venv

- name: rabbit-to-slack| Copy service
  template:
    src: rabbit-to-slack.service.j2
    dest: '/etc/systemd/system/rabbit-to-slack.service'
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart rabbit-to-slack.service

- name: rabbit-to-slack | Start service
  service:
    name: rabbit-to-slack.service
    state: started
    daemon-reload: true
    enabled: true
  become: yes
