---
- name: rabbit-to-slack | Clone repo. branch:'{{ rabbit_to_slack_git_branch }}'
  git:
    repo: https://github.com/Kv-126-DevOps/rabbit_to_slack.git
    dest: '{{ rabbit_to_slack_workdir }}'
    version: '{{ rabbit_to_slack_git_branch }}'

- name: rabbit-to-slack | Install python packeges into virtualenv
  pip:
    requirements: '{{ rabbit_to_slack_workdir }}/requirements.txt'
    virtualenv: '{{ rabbit_to_slack_workdir }}/venv'
  vars:
    ansible_python_interpreter: '/usr/bin/python3'

- name: rabbit-to-slack| Copy service
  template:
    src: rabbit-to-slack.service.j2
    dest: '/etc/systemd/system/rabbit-to-slack.service'
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart rabbit-to-slack.service

- name: rabbit-to-slack | Start service
  service:
    name: rabbit-to-slack.service
    state: started
    enabled: true
