---
- name: Check that Passwords Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ rest_api_postgres_pw }}"
  no_log: true
  
- name: Check that String Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is string }}"
      - "{{ item | length > 0 }}"
    quiet: yes
  loop:
    - "{{ env_class }}"
    - "{{ env_name }}"
    - "{{ env_region }}"
    - "{{ rest_api_git_branch }}"
    - "{{ rest_api_workdir }}"
    - "{{ rest_api_postgres_host }}"
    - "{{ rest_api_postgres_user }}"
    - "{{ rest_api_postgres_db }}"

- name: Check that Integer Variables are set correctly 
  assert:
    that:
      - "{{ item is defined }}"
      - "{{ item is number }}"
    quiet: yes
  loop:
    - "{{ rest_api_postgres_port }}"

- name: rest-api | Clone repo. branch:'{{ rest_api_git_branch }}'
  git:
    repo: https://github.com/Kv-126-DevOps/rest-api.git
    dest: '{{ rest_api_workdir }}'
    version: '{{ rest_api_git_branch }}'
    force: true

- name: rest-api | Install python packeges into virtualenv
  pip:
    requirements: '{{ rest_api_workdir }}/requirements.txt'
    virtualenv: '{{ rest_api_workdir }}/venv'
    virtualenv_command: python3 -m venv

- name: rest-api | Copy service
  template:
    src: rest-api.service.j2
    dest: '/etc/systemd/system/rest-api.service'
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart rest-api.service

- name: rest-api | Start service
  service:
    name: rest-api.service
    state: started
    daemon-reload: true
    enabled: true
  become: yes
