---
- name: rest-api | Clone repo. branch:'{{ rest_api_git_branch }}'
  ansible.builtin.git:
    repo: https://github.com/Kv-126-DevOps/rest-api.git
    dest: '{{ rest_api_workdir }}'
    version: '{{ rest_api_git_branch }}'

- name: rest-api | Install python packeges into virtualenv
  pip:
    requirements: '{{ rest_api_workdir }}/requirements.txt'
    virtualenv: '{{ rest_api_workdir }}/venv'
  vars:
    ansible_python_interpreter: '/usr/bin/python3'

- name: rest-api | Copy service
  template:
    src: rest-api.service.j2
    dest: '{{ rest_api_service_dir }}/rest-api.service'
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - start rest-api.service
