---
- name: rest-api | Clone repo. branch:'{{ rest_api_git_branch }}'
  git:
    repo: https://github.com/Kv-126-DevOps/rest-api.git
    dest: '{{ rest_api_workdir }}'
    version: '{{ rest_api_git_branch }}'
    force: true

- name: rest-api | Install python packeges into virtualenv
  pip:
    requirements: '{{ rest_api_workdir }}/requirements.txt'
    virtualenv: '{{ rest_api_workdir }}/venv'
    virtualenv_command: python3 -m venv

- name: rest-api | Copy service
  template:
    src: rest-api.service.j2
    dest: '/etc/systemd/system/rest-api.service'
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - restart rest-api.service

- name: rest-api | Start service
  service:
    name: rest-api.service
    state: started
    daemon-reload: true
    enabled: true

- name: get IP
  shell: ip -4 addr show eth0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
  register: host_ip

- set_fact:
    rest_api_ip: "{{ host_ip.stdout }}"

- name: Create secure key
  community.aws.aws_ssm_parameter_store:
    name: "rest-api"
    description: "rest-api host IP"
    string_type: "SecureString"
    value: "{{ rest_api_ip }}"
    overwrite_value: "always"
