---
name: CI

on:
  push:
    branches: [main, action-molecule]
  pull_request:
    branches: [main, action-molecule]

jobs:

  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Ansible lint'
        uses: ansible-community/ansible-lint-action@main
        env:
          ANSIBLE_FORCE_COLOR: '1'

  Molecule:
    needs:
      - Lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      
      - name: 'Test Common Role'
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_options: --debug
          molecule_working_dir: ./Kv-126-DevOps/ansible/roles/common
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: 'Front Role'
        uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_options: --debug -e 'env_region=eu-central'
          molecule_working_dir: ./Kv-126-DevOps/ansible/roles/frontend
        env:
          ANSIBLE_FORCE_COLOR: '1'
