name: CI

on:
  push:
    branches: [action-molecule]
  pull_request:
    branches: [action-molecule]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      # Install Node 14
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
          
          #command: "--debug test"
                  
                  
                  
                  