---
name: CI

on:
  push:
    branches: [main, action-molecule]
  pull_request:
    branches: [main, action-molecule]

jobs:

#  Lint:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3

#      - name: 'Ansible lint'
#        uses: ansible-community/ansible-lint-action@main
#        env:
#          ANSIBLE_FORCE_COLOR: '1'

  Molecule:
#    needs:
#      - Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: |
          ls -a
          cd ./Kv-126-DevOps/ansible/roles/common

      - name: Run molecule action
        uses: arista-netdevops-community/action-molecule-avd@v1.0
        with:
          molecule_parentdir: './Kv-126-DevOps/ansible/roles/common'
          molecule_command: 'test'
          molecule_options: '--debug'
          molecule_args: '--all'
          ansible: ansible>=2.10
          check_git: true
          check_git_enforced: true
