name: CI

on:
  push:
    branches: [action-molecule]
  pull_request:
    branches: [action-molecule]

jobs:

  Ansible_Molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
        #  - alpine
          - amazonlinux
        #  - centos
        #  - debian
        #  - fedora
        #  - opensuse
        #  - ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ./Kv-126-DevOps/ansible/roles/common/
          molecule_options: --debug --base-config molecule/_shared/base.yml
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'




  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #    # Checkout the Repo
  #    - uses: actions/checkout@v3

  #    # ansible-lint
  #    - uses: ansible-community/ansible-lint-action@main
                