---
name: CI

on:
  push:
    branches: [action-molecule]
  pull_request:
    branches: [action-molecule]

jobs:

  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ansible-lint
        uses: ansible-community/ansible-lint-action@main
        env:
          ANSIBLE_FORCE_COLOR: '1'

  Molecule_test:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: ./Kv-126-DevOps/ansible/roles/common/
          molecule_options: --debug --base-config molecule/_shared/base.yml
          molecule_command: test
        env:
          ANSIBLE_FORCE_COLOR: '1'
