name: CI

on:
  push:
    branches: [action-molecule]
  pull_request:
    branches: [action-molecule]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      # Install Node 14
      - name: molecule
        uses: robertdebock/molecule-action@4.0.9
        with:
          image: anatolek/docker-amazonlinux2
          tag: latest
          command: lint
          
          #command: "--debug test"
                  
                  
                  
                  