name: CI

on:
  push:
    branches: [action-molecule]
  pull_request:
    branches: [action-molecule]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      - name: molecule
        uses: robertdebock/molecule-action@4.0.9
        with:
          command: lint
                  
                  
                  
                  