name: CI

on:
  push:
    branches: [action-molecule]
  pull_request:
    branches: [action-molecule]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      # ansible-lint
      - uses: ansible-community/ansible-lint-action@main
                