name: CI

on:
  push:
    branches: [action-molecule]
  pull_request:
    branches: [action-molecule]

jobs:

  Ansible_Molecule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./Kv-126-DevOps/ansible/roles/common/ #"${{ github.repository }}"

      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
        env:
          ANSIBLE_FORCE_COLOR: '1'

#      - name: Molecule
#        uses: gofrolist/molecule-action@v2
#        with:
#          molecule_working_dir: ./Kv-126-DevOps/ansible/roles/common/
#          molecule_options: --debug --base-config molecule/_shared/base.yml
#          molecule_command: test
#        env:
#          ANSIBLE_FORCE_COLOR: '1'
                